const SIMPLE_ICONS_CDN = "https://cdn.simpleicons.org";

const topicToIcon: Record<string, { slug: string; color: string }> = {
  go: { slug: "go", color: "00ADD8" },
  golang: { slug: "go", color: "00ADD8" },
  typescript: { slug: "typescript", color: "3178C6" },
  javascript: { slug: "javascript", color: "F7DF1E" },
  react: { slug: "react", color: "61DAFB" },
  nextjs: { slug: "nextdotjs", color: "FFFFFF" },
  "next-js": { slug: "nextdotjs", color: "FFFFFF" },
  python: { slug: "python", color: "3776AB" },
  rust: { slug: "rust", color: "FFFFFF" },
  docker: { slug: "docker", color: "2496ED" },
  postgresql: { slug: "postgresql", color: "4169E1" },
  postgres: { slug: "postgresql", color: "4169E1" },
  mongodb: { slug: "mongodb", color: "47A248" },
  redis: { slug: "redis", color: "FF4438" },
  tailwindcss: { slug: "tailwindcss", color: "06B6D4" },
  tailwind: { slug: "tailwindcss", color: "06B6D4" },
  nodejs: { slug: "nodedotjs", color: "5FA04E" },
  node: { slug: "nodedotjs", color: "5FA04E" },
  "node-js": { slug: "nodedotjs", color: "5FA04E" },
  bun: { slug: "bun", color: "FFFFFF" },
  vite: { slug: "vite", color: "646CFF" },
  svelte: { slug: "svelte", color: "FF3E00" },
  vue: { slug: "vuedotjs", color: "4FC08D" },
  angular: { slug: "angular", color: "0F0F11" },
  firebase: { slug: "firebase", color: "DD2C00" },
  supabase: { slug: "supabase", color: "3FCF8E" },
  aws: { slug: "amazonwebservices", color: "232F3E" },
  linux: { slug: "linux", color: "FCC624" },
  git: { slug: "git", color: "F05032" },
  github: { slug: "github", color: "FFFFFF" },
  csharp: { slug: "csharp", color: "512BD4" },
  "c-sharp": { slug: "csharp", color: "512BD4" },
  dotnet: { slug: "dotnet", color: "512BD4" },
  ".net": { slug: "dotnet", color: "512BD4" },
  java: { slug: "openjdk", color: "FFFFFF" },
  html: { slug: "html5", color: "E34F26" },
  css: { slug: "css3", color: "1572B6" },
  sass: { slug: "sass", color: "CC6699" },
  graphql: { slug: "graphql", color: "E10098" },
  express: { slug: "express", color: "FFFFFF" },
  flask: { slug: "flask", color: "FFFFFF" },
  django: { slug: "django", color: "092E20" },
  "machine-learning": { slug: "tensorflow", color: "FF6F00" },
  ai: { slug: "openai", color: "412991" },
  security: { slug: "letsencrypt", color: "003A70" },
  sqlite: { slug: "sqlite", color: "003B57" },
  mysql: { slug: "mysql", color: "4479A1" },
  webpack: { slug: "webpack", color: "8DD6F9" },
  figma: { slug: "figma", color: "F24E1E" },
  vercel: { slug: "vercel", color: "FFFFFF" },
  netlify: { slug: "netlify", color: "00C7B7" },
  swift: { slug: "swift", color: "F05138" },
  kotlin: { slug: "kotlin", color: "7F52FF" },
  ruby: { slug: "ruby", color: "CC342D" },
  php: { slug: "php", color: "777BB4" },
  electron: { slug: "electron", color: "47848F" },
  prisma: { slug: "prisma", color: "2D3748" },
  pandas: { slug: "pandas", color: "150458" },
  scikit: { slug: "scikitlearn", color: "F7931E" },
  "scikit-learn": { slug: "scikitlearn", color: "F7931E" },
};

export function getTopicIconUrl(topic: string): string | null {
  const entry = topicToIcon[topic.toLowerCase()];
  if (!entry) return null;
  return `${SIMPLE_ICONS_CDN}/${entry.slug}/${entry.color}`;
}
